
import React from 'react';
import { useValuation } from '@/lib/state/ValuationState';
import { formatCurrency } from '@/lib/utils';

export default function PrintView() {
    const {
        context,
        berkusValuation,
        scorecardValuation,
        vcValuation,
        riskFactorValuation,
        costToDuplicateValuation,
        vcInputs,
        scorecardInputs
    } = useValuation();

    // Calculate Triangulated Value (Average of non-zero methods)
    const methods = [berkusValuation, scorecardValuation, vcValuation, riskFactorValuation, costToDuplicateValuation].filter(v => v > 0);
    const averageValuation = methods.length > 0 ? methods.reduce((a, b) => a + b, 0) / methods.length : 0;

    return (
        <div className="p-8 max-w-[210mm] mx-auto bg-white text-black print:p-0">
            {/* Header */}
            <div className="border-b-2 border-black pb-4 mb-8 flex justify-between items-end">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">Investment Committee Memo</h1>
                    <p className="text-gray-600 mt-1">Valuation Analysis Report</p>
                </div>
                <div className="text-right">
                    <p className="font-bold">{new Date().toLocaleDateString()}</p>
                    <p className="text-sm text-gray-500">Generated by Valuation Engine</p>
                </div>
            </div>

            {/* Executive Summary */}
            <div className="mb-8 bg-gray-50 p-6 border border-gray-200 rounded-lg">
                <h2 className="text-sm font-bold uppercase tracking-wider text-gray-500 mb-2">Executive Summary</h2>
                <div className="flex justify-between items-center">
                    <div>
                        <p className="text-lg font-medium">Triangulated Pre-Money Valuation</p>
                        <p className="text-4xl font-bold mt-1">{formatCurrency(averageValuation)}</p>
                    </div>
                    <div className="text-right space-y-1">
                        <p><span className="font-semibold">Sector:</span> {context.sector}</p>
                        <p><span className="font-semibold">Region:</span> {context.region}</p>
                        <p><span className="font-semibold">Stage:</span> Pre-Revenue / Seed</p>
                    </div>
                </div>
            </div>

            {/* Methodology Breakdown */}
            <div className="mb-8">
                <h3 className="text-xl font-bold mb-4 border-b border-gray-200 pb-2">Methodology Breakdown</h3>
                <table className="w-full text-left text-sm">
                    <thead>
                        <tr className="border-b border-gray-300">
                            <th className="py-2 font-bold">Method</th>
                            <th className="py-2 font-bold text-right">Valuation</th>
                            <th className="py-2 font-bold text-right">Weight</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        <tr>
                            <td className="py-3">Berkus Method</td>
                            <td className="py-3 text-right font-mono">{formatCurrency(berkusValuation)}</td>
                            <td className="py-3 text-right text-gray-500">20%</td>
                        </tr>
                        <tr>
                            <td className="py-3">Scorecard Method</td>
                            <td className="py-3 text-right font-mono">{formatCurrency(scorecardValuation)}</td>
                            <td className="py-3 text-right text-gray-500">20%</td>
                        </tr>
                        <tr>
                            <td className="py-3">VC Method</td>
                            <td className="py-3 text-right font-mono">{formatCurrency(vcValuation)}</td>
                            <td className="py-3 text-right text-gray-500">20%</td>
                        </tr>
                        <tr>
                            <td className="py-3">Risk Factor Summation</td>
                            <td className="py-3 text-right font-mono">{formatCurrency(riskFactorValuation)}</td>
                            <td className="py-3 text-right text-gray-500">20%</td>
                        </tr>
                        <tr>
                            <td className="py-3">Cost-to-Duplicate</td>
                            <td className="py-3 text-right font-mono">{formatCurrency(costToDuplicateValuation)}</td>
                            <td className="py-3 text-right text-gray-500">20%</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            {/* Key Assumptions */}
            <div className="grid grid-cols-2 gap-8 mb-8">
                <div>
                    <h3 className="text-lg font-bold mb-3 border-b border-gray-200 pb-1">VC Assumptions</h3>
                    <ul className="space-y-2 text-sm">
                        <li className="flex justify-between">
                            <span className="text-gray-600">Exit Revenue:</span>
                            <span className="font-medium">{formatCurrency(vcInputs.exitRevenue)}</span>
                        </li>
                        <li className="flex justify-between">
                            <span className="text-gray-600">Exit Multiple:</span>
                            <span className="font-medium">{vcInputs.exitMultiple}x</span>
                        </li>
                        <li className="flex justify-between">
                            <span className="text-gray-600">Required ROI:</span>
                            <span className="font-medium">{vcInputs.requiredROI}x</span>
                        </li>
                        <li className="flex justify-between">
                            <span className="text-gray-600">Investment Ask:</span>
                            <span className="font-medium">{formatCurrency(vcInputs.investmentAmount)}</span>
                        </li>
                    </ul>
                </div>
                <div>
                    <h3 className="text-lg font-bold mb-3 border-b border-gray-200 pb-1">Qualitative Factors</h3>
                    <ul className="space-y-2 text-sm">
                        <li className="flex justify-between">
                            <span className="text-gray-600">Team Strength:</span>
                            <span className="font-medium">{(scorecardInputs.teamScore * 100).toFixed(0)}%</span>
                        </li>
                        <li className="flex justify-between">
                            <span className="text-gray-600">Product Strength:</span>
                            <span className="font-medium">{(scorecardInputs.productScore * 100).toFixed(0)}%</span>
                        </li>
                        <li className="flex justify-between">
                            <span className="text-gray-600">Market Opportunity:</span>
                            <span className="font-medium">{(scorecardInputs.opportunityScore * 100).toFixed(0)}%</span>
                        </li>
                    </ul>
                </div>
            </div>

            {/* Footer */}
            <div className="mt-12 pt-8 border-t border-gray-200 text-center text-xs text-gray-400">
                <p>Confidential & Proprietary. For Internal Use Only.</p>
            </div>
        </div>
    );
}
